# Generated by Django 4.2.7 on 2023-11-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_article_is_active_article_is_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
