# Generated by Django 4.2.7 on 2023-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review_is_active_alter_review_like_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='original_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
